---
  Resources:
    javahomestudents:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.myTable}
        AttributeDefinitions:
          - AttributeName: year
            AttributeType: S
          - AttributeName: time_stamp
            AttributeType: S
        KeySchema:
          - AttributeName: year
            KeyType: HASH
          - AttributeName: time_stamp
            KeyType: RANGE
        # Set the capacity based on the stage
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
